version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres        # имя пользователя
      POSTGRES_PASSWORD: postgres    # пароль
      POSTGRES_DB: my_database       # имя создаваемой БД
    ports:
      - "5432:5432"                  # пробрасываем порт
    volumes:
      - db_data:/var/lib/postgresql/data  # сохраняем данные при перезапуске

volumes:
  db_data: